# See https://wiki.hyprland.org/Configuring/Binds/
#!
##! User
bind = Ctrl+Super, Slash, exec, xdg-open ~/.config/illogical-impulse/config.json # Edit shell config
bind = Ctrl+Super+Alt, Slash, exec, xdg-open ~/.config/hypr/custom/keybinds.conf # Edit extra keybinds

# Add stuff here
# Use #! to add an extra column on the cheatsheet
# Use ##! to add a section in that column
# Add a comment after a bind to add a description, like above

# The following mappings use the key codes to better support various keyboard layouts
# 1 is code:10, 2 is code 11, etc

# Move windows
bind = Super CTRL, left, movewindow, l
bind = Super CTRL, right, movewindow, r
bind = Super CTRL, up, movewindow, u
bind = Super CTRL, down, movewindow, d

# Move focus with mainMod + arrow keys
bind = Super, left, movefocus, l
bind = Super, right, movefocus, r
bind = Super, up, movefocus, u
bind = Super, down, movefocus, d

# Switch workspaces with mainMod + [0-9] 
bind = Super, code:10, workspace, 1
bind = Super, code:11, workspace, 2
bind = Super, code:12, workspace, 3
bind = Super, code:13, workspace, 4
bind = Super, code:14, workspace, 5
bind = Super, code:15, workspace, 6
bind = Super, code:16, workspace, 7
bind = Super, code:17, workspace, 8
bind = Super, code:18, workspace, 9
bind = Super, code:19, workspace, 10

# Move active window and follow to workspace mainMod + SHIFT [0-9]
bind = Super SHIFT, code:10, movetoworkspace, 1
bind = Super SHIFT, code:11, movetoworkspace, 2
bind = Super SHIFT, code:12, movetoworkspace, 3
bind = Super SHIFT, code:13, movetoworkspace, 4
bind = Super SHIFT, code:14, movetoworkspace, 5
bind = Super SHIFT, code:15, movetoworkspace, 6
bind = Super SHIFT, code:16, movetoworkspace, 7
bind = Super SHIFT, code:17, movetoworkspace, 8
bind = Super SHIFT, code:18, movetoworkspace, 9
bind = Super SHIFT, code:19, movetoworkspace, 10
bind = Super SHIFT, bracketleft, movetoworkspace, -1 # brackets [ or ]
bind = Super SHIFT, bracketright, movetoworkspace, +1

# Move active window to a workspace silently mainMod + CTRL [0-9]
bind = Super CTRL, code:10, movetoworkspacesilent, 1
bind = Super CTRL, code:11, movetoworkspacesilent, 2
bind = Super CTRL, code:12, movetoworkspacesilent, 3
bind = Super CTRL, code:13, movetoworkspacesilent, 4
bind = Super CTRL, code:14, movetoworkspacesilent, 5
bind = Super CTRL, code:15, movetoworkspacesilent, 6
bind = Super CTRL, code:16, movetoworkspacesilent, 7
bind = Super CTRL, code:17, movetoworkspacesilent, 8
bind = Super CTRL, code:18, movetoworkspacesilent, 9
bind = Super CTRL, code:19, movetoworkspacesilent, 10
bind = Super CTRL, bracketleft, movetoworkspacesilent, -1 # brackets [ or ]
bind = Super CTRL, bracketright, movetoworkspacesilent, +1

# Scroll through existing workspaces with mainMod + scroll
bind = Super, mouse_down, workspace, e+1
bind = Super, mouse_up, workspace, e-1
bind = Super, period, workspace, e+1
bind = Super, comma, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = Super, mouse:272, movewindow
bindm = Super, mouse:273, resizewindow
