[ids]
*

[main]
# Tap => Esc
# Hold => ctrl_vim layer
capslock = overload(ctrl_vim, esc)

[ctrl_vim]
# Toggle persistent vim mode
space = toggle(vim_mode)

[vim_mode]
# Exit vim mode
capslock = clear()

# Vim-style scrolling
j = macro(scrolldown scrolldown)
k = macro(scrollup scrollup)
